
POST http://localhost:4000/profile/create
content-type: application/json

{
    "description": "description",
    "school": "MIU",
    "userId": "655a5b49f03166a3b186acc1",
    "skills": ["Java"],
    "mobile": "mobile"
}



###



GET http://localhost:4000/skills/



###


POST http://localhost:4000/skills/create
Content-Type: application/json

{
    "skill" : "SQL",
    "img":"https://tipa.in/wp-content/uploads/2021/05/Online-courses.jpg"
}


###


GET http://localhost:4000/profile/findOne/655a5b49f03166a3b186acc1



###


GET http://localhost:4000/profile/all


###


GET http://localhost:4000/profile/findWithSkill/Java


###


POST http://localhost:4000/mailer/
Content-Type: application/json

{
    "sender": "655a5b49f03166a3b186acc1",
    "recipient": "655a5b49f03166a3b186acc1"
}
